foods_analyser_task:
  description: >
    You will **always** use the File Read Tool to retrive the foods and their asociated information. 
    The file which contains the foods is located in {file_path}.
    Do not create information unrelated to the file.
    Display all the given items that are already provided using the File Read Tool, don't create your own input.
    You will have multiple item objects.
    Ensure your displaying are precise just like in the provided file.
  expected_output: >
    All the foods in the JSON file with their proprieties.
  agent: foods_analyser


calorie_calculation_task:
  description: >
    You will **always** use the File Read Tool to retrive the foods and their asociated information. 
    The file which contains the foods is located in {file_path}.
    Do not create information unrelated to the file.
    Extract all of the values of the propriety "calories" of each item and then return the value of the sum of all of the values.
    The calories are already provided by the agent using the File Read Tool, don't create your own input.
    Ensure your calculations are precise.
  expected_output: >
    The total calorie count for all the foods in the provided file and also each item with its coresponding number of calories.
  agent: calorie_calculator
 


protein_analysis_task:
  description: >
    You will **always** use the File Read Tool to retrive the foods and their asociated information. 
    The file which contains the foods is located in {file_path}.
    Do not create information unrelated to the file.
    Extract all of the values of the propriety "protein_g" of each item and then return the highest value out of all of the values.
    The protein is already provided by the agent using the File Read Tool, don't create your own input.
    Always name one item.
  expected_output: >
    The name of the food with the highest protein content in the provided file and its corresponding protein value.
  agent: protein_analyzer
